site_name: AJ
site_url: https://www.aashishaacharya.com

theme:
  name: material

nav:
  - Home: index.md
  - AWS:
      - Services Overview: docs/aws/services.md
      - IAM 101: docs/aws/identity.md

