site_name: AJ
site_url: https://www.aashishaacharya.com

theme:
  name: material

nav:
  - AWS:
      - Services Overview: aws/services.md
      - IAM 101: aws/identity.md
  - Projects:
      - Overview: project/index.md
  - Blog & Newsletter:
      - Link: aws/link.md

